npm uninstall @udecode/slate-plugins
npm uninstall @udecode/slate-plugins-normalizers
npm uninstall @udecode/slate-plugins-styled-components
npm uninstall @udecode/slate-plugins-select
npm uninstall @udecode/slate-plugins-paragraph
npm uninstall @udecode/slate-plugins-trailing-block
npm uninstall @udecode/slate-plugins-table
npm uninstall @udecode/slate-plugins-reset-node
npm uninstall @udecode/slate-plugins-mention
npm uninstall @udecode/slate-plugins-media-embed
npm uninstall @udecode/slate-plugins-md-serializer
npm uninstall @udecode/slate-plugins-node-id
npm uninstall @udecode/slate-plugins-highlight
npm uninstall @udecode/slate-plugins-heading
npm uninstall @udecode/slate-plugins-table-ui
npm uninstall @udecode/slate-plugins-toolbar
npm uninstall @udecode/slate-plugins-link
npm uninstall @udecode/slate-plugins-image
npm uninstall @udecode/slate-plugins-placeholder
npm uninstall @udecode/slate-plugins-font
npm uninstall @udecode/slate-plugins-list-ui
npm uninstall @udecode/slate-plugins-html-serializer
npm uninstall @udecode/slate-plugins-kbd
npm uninstall @udecode/slate-plugins-media-embed-ui
npm uninstall @udecode/slate-plugins-mention-ui
npm uninstall @udecode/slate-plugins-find-replace-ui
npm uninstall @udecode/slate-plugins-image-ui
npm uninstall @udecode/slate-plugins-find-replace
npm uninstall @udecode/slate-plugins-link-ui
npm uninstall @udecode/slate-plugins-font-ui
npm uninstall @udecode/slate-plugins-list
npm uninstall @udecode/slate-plugins-code-block
npm uninstall @udecode/slate-plugins-basic-elements
npm uninstall @udecode/slate-plugins-block-quote
npm uninstall @udecode/slate-plugins-alignment
npm uninstall @udecode/slate-plugins-basic-marks
npm uninstall @udecode/slate-plugins-autoformat
npm uninstall @udecode/slate-plugins-dnd
npm uninstall @udecode/slate-plugins-ast-serializer
npm uninstall @udecode/slate-plugins-break
npm uninstall @udecode/slate-plugins-alignment-ui
npm uninstall @udecode/slate-plugins-common
npm uninstall @udecode/slate-plugins-code-block-ui
npm uninstall @udecode/slate-plugins-core
npm uninstall @udecode/slate-plugins-block-quote-ui